---
site_author: Co-op Cloud
site_name: Co-op Cloud
site_url: https://cloud.autonomic.zone

theme:
  name: material
  features:
    - navigation.instant
    - toc.integrate
  palette:
    primary: light pink
    accent: purple

copyright: Copyleft ðŸ„¯ 2021 The Co-operative Cloud

markdown_extensions:
  - meta
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - A co-operative alternative: index.md
  - Getting started guide:
      - Architecture overview: overview.md
      - Deploy your first application: deploy.md
  - Application catalogue: apps.md
  - Tutorials:
      - Package your first application: package.md
  - Frequently asked questions: faq.md
  - Get in touch: contact.md

plugins:
  - search
  - awesome-pages

repo_name: coop-cloud/docs.cloud.autonomic.zone
repo_url: https://git.autonomic.zone/coop-cloud/docs.cloud.autonomic.zone
edit_uri: _edit/main/docs/
