---
site_author: Co-op Cloud
site_name: Co-op Cloud
site_url: https://coopcloud.tech

theme:
  name: material
  features:
    - navigation.instant
    - toc.integrate
  palette:
    primary: light pink
    accent: purple

copyright: Copyleft ðŸ„¯ 2021 The Co-operative Cloud

markdown_extensions:
  - meta
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - A co-operative alternative: index.md
  - Getting started guide:
      - Architecture overview: overview.md
      - Deploy your first app: deploy.md
  - App catalogue: apps.md
  - Tutorials:
      - Package your first app: package.md
      - Manage your app configuration: config.md
      - Manage secret data: secrets.md
      - Back-up and restore an app: backup-restore.md
      - Scale an app up to handle more traffic: scale.md
      - Roll an app back to a previous version: rollback.md
  - App config guide: app-config-guide.md
  - Packager guide: packager-guide.md
  - Frequently asked questions: faq.md
  - Roadmap: roadmap.md
  - Contributing guide: contribute.md
  - Get in touch: contact.md
  - Credits & thanks: credits.md

plugins:
  - search
  - awesome-pages

repo_name: coop-cloud/docs.cloud.autonomic.zone
repo_url: https://git.autonomic.zone/coop-cloud/docs.cloud.autonomic.zone
edit_uri: _edit/main/docs/
